### ISSUE TITLE
Cannot load SDK in Python 3.5.2

### ISSUE THREAD

**Issue by chaoran** [intrinio/intrinio-realtime-python-sdk#2]
```
$ python
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from intriniorealtime.client import IntrinioRealtimeClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chaoran/.venv/zzy/lib/python3.5/site-packages/intriniorealtime/client.py", line 66
    raise ValueError(f"Parameter 'provider' is invalid, use one of {PROVIDERS}")
                                                                              ^
SyntaxError: invalid syntax
>>> 
```

**Comment by bgse** [comment]
`f"Parameter 'provider' is invalid, use one of {PROVIDERS}")`

Since `f-strings` are a [Python 3.6 feature](https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings), this would indeed mean that you are out of luck with Python 3.5 at this time.

**Comment by civilframe** [comment]
We are working to support earlier versions of Python.

**Comment by bgse** [comment]
@civilframe Didn't have the time for a proper PR, but from the looks of it supporting 3.5 should be a pretty low hanging fruit, as well as a major adoption-breaker cleared seeing that is the default shipping with Ubuntu 16.04 and derivates.
