### ISSUE TITLE
Socket is Already Closed Error

### ISSUE THREAD

**Issue by sirusss** [intrinio/intrinio-realtime-python-sdk#5]
I have been frequently running into this problem which occurs at seemingly random times for no apparent reason, without much detail.

Originally I thought this problem could be due to leaving my connection with Intrinio open indefinitely. I have instituted strict, daily, websocket connect/disconnect times but run into the same issue:

`2018-01-03 23:00:35,024 - scriptpy - ERROR - Websocket ERROR: Connection is already closed.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/user1/.local/lib/python3.4/site-packages/intriniorealtime/client.py", line 317, in run
    self.client.ws.send(json.dumps(msg))
  File "/usr/local/lib/python3.4/dist-packages/websocket/_app.py", line 117, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
`

Any idea why this keeps being an issue? Is there a proper way that the websocket connection should be opened and closed? Does the client object need to be recycled in a certain way to reconnect the websocket without exiting the script first?

**Comment by sirusss** [comment]
Update on this issue: I notice the error occurs **at the same time** everyday.

**Comment by civilframe** [comment]
@sirusss The server is reset daily. The SDK should reconnect gracefully. The error you are getting suggests this may not be the case. I will look into this.

**Comment by sirusss** [comment]
Thanks for the reply, @civilframe . The log in the OP is in the CST timezone if that helps. Does the server reset at 9PM PST, daily?

**Comment by civilframe** [comment]
Yes, the reset is at 9PM PST daily. You should be able to call `client.disconnect()` to disconnect gracefully, then `client.connect()` to reconnect.
